# Generated by Django 4.0.2 on 2022-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovicka', '0002_alter_odpoved_spravne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvicenie',
            options={'verbose_name_plural': 'Cvicenia'},
        ),
        migrations.AlterModelOptions(
            name='odpoved',
            options={'verbose_name_plural': 'Odpovede'},
        ),
        migrations.AlterModelOptions(
            name='pokus',
            options={'verbose_name_plural': 'Pokusy'},
        ),
        migrations.AlterModelOptions(
            name='slovicko',
            options={'verbose_name_plural': 'Slovicka'},
        ),
        migrations.AddField(
            model_name='cvicenie',
            name='typ',
            field=models.CharField(choices=[('Dopisovanie', 'Dopisovanie'), ('Spajanie', 'Spajanie')], default='Dopisovanie', max_length=100),
        ),
        migrations.AlterField(
            model_name='cvicenie',
            name='trieda',
            field=models.CharField(choices=[('1.A', '1.A'), ('2.A', '2.A'), ('5.A', '5.A')], max_length=100),
        ),
    ]
